### ISSUE TITLE
Project Progress

### ISSUE THREAD

**Issue by tuckergol** [tuckergol/frontgang#1]
### Overall Progress

**3/14/24**
- Frontend base completed --> formats data in JSON
  - Still need some backend model work for frontend to produce output (API, model)

**3/15/24**
- Finding suitable CSV for personalized ML --> likely restaurant data
  - Restaurant data combines previous members' CPT topics: food/cooking + stocks with business/industry
- Complete base Titanic model (backend + frontend) 

**3/16/24**
- Found dataset for custom data ML portion
  - Data from online food orders (CPT project topic relation - combines stocks in business/industry aspect + food because of industry topic)
  - May filter out unnecessary info

**3/18/24**
- Finished up Titanic data over the weekend and early today
   - Survival + death probability displayed
   - Progress further in using new ML data, apply CPT project topics...
 - Create .ipynb/overall outline to demo custom data
 - Filter out unnecessary info in CSV file data for new ML data

**3/19/24**
- Work on custom data ML
  - Used new [CSV file](https://github.com/tuckergol/backgang/blob/main/filtered_data.csv): bakery data
    - Use specific time of day, general time of day, and day of week to determine purchased food item

**3/20/24**
- First review for ML project
  - Scored 0.93/1 for completion of Titanic ML model + base/start on custom data ML model
  - Feedback...
    - [x] Make alert/pop-up for more obvious death probability display following call on predict function for Titanic model
    - [x] Implement data for __init__ for defining commands to generate data in [main.py](https://github.com/tuckergol/backgang/blob/main/main.py)

**Friday → Weekend (3/22/24 → 3/24/24)**
- Finalized feature
  - Completed ML custom data
    - Spent good amount of time on call to communicate and finish custom ML system

**3/27/24**
- Finalized ML project
  - Topped off custom data set by adding an additional form but using a dataset with no coffee for reduced skew and more accurate/varied results (since coffee makes up nearly 1/4 of the entire dataset, you're very likely to get coffee normally)

**Comment by varunm532** [comment]
## Frontend progress

- 3/13/24
    - found suitable frontend table and integrated it
    - fixed issues with header and change from scss file to css file for ease 
- 3/14/24
    - integrated dropdown menu and fixed issue in css file the prevented text to be shown in dropdown menu
- 3/15/24
    - Fixed styling problems and restructured js to work properly to create json payload
- 3/18/24
    - Connected frontend to backend and format changes with inputs and json payload
-3/24/24
    - Connected frontend to backend and farmat changes with inputs and json payload for food prediction
 
## Backend progress

- 3/23/34
    - Made Model and Api for food prediction and followed teacher prodedure
